TrajectoryPlannerROS:
  max_vel_x: 0.20
  min_vel_x: 0.1
  max_vel_theta: 1.0
  min_in_place_vel_theta: 0.4

  acc_lim_x: 0.5
  acc_lim_theta: 1.0

  holonomic_robot: false

  meter_scoring: true

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.157
  xy_goal_tolerance: 0.1
  latch_xy_goal_tolerance: false

  # Forward Simulation Parameters
  sim_time: 2.0
  sim_granularity: 0.02
  angular_sim_granularity: 0.02
  vx_samples: 6
  vtheta_samples: 20
  controller_frequency: 20.0

  # Trajectory scoring parameters
  occdist_scale:  0.1 #The weighting for how much the controller should attempt to avoid obstacles. default 0.01
